[keyboard-nav] Sync with trunk rev 1085.
git-svn-id: https://s.snth.net/svn/neverball/branches/keyboard-nav@1086 78b8d119-cf0a-0410-b17c-f493084dd1d7

diff --git a/Makefile.mingw b/Makefile.mingw
--- a/Makefile.mingw
+++ b/Makefile.mingw
@@ -1,22 +1,89 @@
-#
-# A simple makefile to compile Neverball, Neverputt and mapc Windows binaries,
-# with mingw32.  You must have wine installed to compile maps.  You need to use
-# a script which defines the variables of your Linux mingw32 cross-compilation
-# environment (PATH, PREFIX, TARGET, CC, CXX, ...) to run this makefile. This
-# scripts is usually named "cross-make.sh".  Currently you need to have SDL,
-# SDL_ttf and SDL_image DLLs in the makefile directory to compile maps.
-#
-# Mehdi.
+export EXT= .exe
+
+#-----------------------------------------------------------------------------
 
 include Makefile
 
-OGL_LIBS := -lm -lopengl32 -lglu32
+#-----------------------------------------------------------------------------
 
-MAPC_TARG := mapc.exe
-MAPC_EXEC := wine mapc.exe
-BALL_TARG := neverball.exe
-PUTT_TARG := neverputt.exe
+WINE= wine
 
-BASE_LIBS := $(SDL_LIBS) -lSDL_image -lintl
-LIBS := $(X11_PATH) -lSDL_mixer $(SDL_LIBS) -lSDL_ttf -lSDL_image \
-	$(FT2_LIBS) $(OGL_LIBS) -lintl -lpng -lz -ljpeg
+OGL_LIBS= -lm -lopengl32
+BASE_LIBS= -lSDL -lSDL_image -lintl
+
+LIBS= \
+	$(SDL_LIBS) -lSDL_image -lSDL_mixer -lSDL_ttf \
+	$(OGL_LIBS) $(PNG_LIBS) -lintl
+
+#-----------------------------------------------------------------------------
+
+INSTALLER= ../neverball-$(VERSION)-setup.exe
+
+MAKENSIS= makensis
+MAKENSIS_FLAGS= -DVERSION=$(VERSION) -DOUTFILE=$(INSTALLER)
+
+TODOS= todos
+FROMDOS= fromdos
+CP= cp
+
+TEXT_DOCS= \
+	doc/AUTHORS \
+	doc/MANUAL  \
+	CHANGES     \
+	COPYING     \
+	README
+
+TXT_DOCS= $(TEXT_DOCS:%=%.txt)
+
+#-----------------------------------------------------------------------------
+
+.PHONY: setup
+setup: $(INSTALLER)
+
+$(INSTALLER): install-dlls convert-text-files all tools
+	$(MAKENSIS) $(MAKENSIS_FLAGS) -nocd scripts/neverball.nsi
+
+# This fails on MSYS due to a bug in the shipped version of make (3.79.1).
+# $(INSTALLER): LDFLAGS += -s
+$(INSTALLER): LDFLAGS := $(LDFLAGS) -s
+
+.PHONY: clean-setup
+clean-setup: clean
+	# $(RM) $(INSTALLER)
+	$(RM) install-dlls.sh *.dll $(TXT_DOCS)
+	find data -name "*.txt" -exec $(FROMDOS) {} \;
+	cd tools && $(MAKE) clean
+
+#-----------------------------------------------------------------------------
+
+.PHONY: install-dlls
+install-dlls: install-dlls.sh
+	sh $<
+
+install-dlls.sh:
+	if ! sh scripts/gen-install-dlls.sh > $@; then \
+	    $(RM) $@; \
+	    exit 1; \
+	fi
+	@echo --------------------------------------------------------
+	@echo You can probably ignore any file-not-found errors above.
+	@echo Now edit $@ to your needs before restarting make.
+	@echo --------------------------------------------------------
+	@exit 1
+
+#-----------------------------------------------------------------------------
+
+.PHONY: convert-text-files
+convert-text-files: $(TXT_DOCS)
+	find data -name "*.txt" -exec $(TODOS) {} \;
+
+%.txt: %
+	$(CP) $< $@
+	$(TODOS) $@
+
+#-----------------------------------------------------------------------------
+
+tools:
+	cd tools && $(MAKE)
+
+#-----------------------------------------------------------------------------
